---

language: generic
dist: xenial
sudo: required

script:
- sudo apt-get update
- sudo apt-get -y dist-upgrade
- sudo apt-get -y install wget make gawk gcc bc bison flex xorriso libelf-dev libssl-dev
- ./minimal.sh
